name: Send emails daily
on:
  workflow_dispatch:
permissions:
  contents: write
  issues: write
  pages: write
  id-token: write
jobs:
  daily:
    uses: ./.github/workflows/daily-fetch.yml
    secrets: inherit
