name: Send emails daily
on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Setup uv
        uses: astral-sh/setup-uv@v7.1.4

      - name: Prepare config
        env:
          CUSTOM_CONFIG: ${{ vars.CUSTOM_CONFIG }}
        run: bash .github/scripts/prepare-config.sh

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          SENDER: ${{ secrets.SENDER }}
          RECEIVER: ${{ secrets.RECEIVER }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          SILICONFLOW_API_KEY: ${{ secrets.SILICONFLOW_API_KEY }}
        run: |
          uv run --locked src/zotero_arxiv_daily/main.py
